import { createFileRoute } from '@tanstack/react-router';
import { useState } from 'react';
import { ArrowUpRight } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { PageIntro,WhatsAppButton } from '@/components/storefront';
import { customMessage,pageHead,whatsapp } from '@/lib/catalog';
export const Route=createFileRoute('/custom-orders')({head:()=>pageHead('Custom Orders','Discuss personalized cards, hampers, artwork and memory gifts with Akarshan Creations. Share your ideas and begin a custom enquiry on WhatsApp.'),component:CustomOrders});
const steps=[['Share your idea','Tell us the occasion, the creation you have in mind, and any inspiration or references.'],['Make it personal','We’ll discuss design, personalization, contents where relevant, and the final quotation.'],['Confirm your order','Your order is confirmed once the final details are agreed upon and full advance payment is received.'],['Creation & delivery','Typical preparation takes 5–7 days. Shipping transit is additional; discuss your required date with us.']];
function CustomOrders(){const [idea,setIdea]=useState('');const [occasion,setOccasion]=useState('');const [theme,setTheme]=useState('');const [budget,setBudget]=useState('');const [date,setDate]=useState('');function submit(e:React.FormEvent){e.preventDefault();const message=`Hi Akarshan Creations! I'd like to discuss a custom creation.\nCreation idea: ${idea}\nOccasion: ${occasion||'I’d like your guidance'}\nDesign / theme: ${theme||'To discuss'}\nBudget: ${budget||'To discuss'}\nRequired delivery date: ${date||'To discuss'}\nI can share reference images here on WhatsApp. Please confirm the options, final price and feasible timing.`;window.open(whatsapp(message),'_blank','noopener,noreferrer')}return <><PageIntro eyebrow="YOUR IDEA, MADE PERSONAL" title="Imagine it. Let’s create it.">A personalized card, a thoughtful hamper, handmade artwork, or a memory book — tell us what you’re imagining, and we’ll discuss the possibilities.</PageIntro><section className="container"><div className="steps-grid">{steps.map(([title,text],i)=><div key={title}><div className="step-number">0{i+1}</div><h3>{title}</h3><p>{text}</p></div>)}</div><div className="custom-form-section"><div><span className="eyebrow">LET’S START WITH YOUR IDEA</span><h2>All the little details that make it yours.</h2><p>Share a few thoughts to begin your WhatsApp conversation. Designs, pricing, and delivery details are agreed with us before an order is confirmed.</p><p>Have reference images? You can share them directly in the conversation.</p><WhatsAppButton message={customMessage} variant="ghost">Talk to us instead <ArrowUpRight size={16}/></WhatsAppButton></div><form className="custom-form" onSubmit={submit}><label className="form-wide">What would you like to create?<textarea rows={3} required placeholder="A personalized gift hamper, a memory book…" value={idea} onChange={e=>setIdea(e.target.value)}/></label><label>Occasion<select value={occasion} onChange={e=>setOccasion(e.target.value)}><option value="">Choose an occasion</option>{['Birthday','Anniversary',"Valentine’s Day",'Festival','Milestone','Just because','Other'].map(o=><option key={o}>{o}</option>)}</select></label><label>Preferred design or theme<input value={theme} onChange={e=>setTheme(e.target.value)} placeholder="Colours, style, little details…"/></label><label>Budget (optional, INR)<input value={budget} onChange={e=>setBudget(e.target.value)} placeholder="Your approximate budget"/></label><label>Required delivery date (optional)<input type="date" value={date} onChange={e=>setDate(e.target.value)}/></label><Button className="form-wide" type="submit">Continue on WhatsApp <ArrowUpRight size={16}/></Button><small className="form-wide">This opens a draft message on WhatsApp. You can edit it before sending. It does not place an order or confirm a delivery date.</small></form></div></section></>;}
