import { createFileRoute } from '@tanstack/react-router';
import { useEffect, useState } from 'react';
import * as Dialog from '@radix-ui/react-dialog';
import { ChevronLeft,ChevronRight,X } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { CustomBanner, PageIntro } from '@/components/storefront';
import { categories,pageHead,products } from '@/lib/catalog';
export const Route=createFileRoute('/gallery')({head:()=>pageHead('Gallery','Explore real handmade art, personalized gifts, memory books, gift hampers and accessories from Akarshan Creations.'),component:Gallery});
function Gallery(){const [category,setCategory]=useState('All Creations');const [index,setIndex]=useState<number|null>(null);const filtered=products.filter(p=>category==='All Creations'||p.category===category);const selected=index===null?undefined:filtered[index];function move(delta:number){setIndex(i=>i===null?null:(i+delta+filtered.length)%filtered.length)}useEffect(()=>{if(index===null)return;function key(e:KeyboardEvent){if(e.key==='ArrowLeft')move(-1);if(e.key==='ArrowRight')move(1)}window.addEventListener('keydown',key);return()=>window.removeEventListener('keydown',key)},[index,filtered.length]);return <><PageIntro eyebrow="A GLIMPSE OF WHAT WE CREATE" title="Our Creative World">Real creations, little personal touches, and the details that make them special.</PageIntro><section className="container catalog-section"><div className="filters">{categories.map(c=><Button key={c} variant={category===c?'default':'outline'} aria-pressed={category===c} onClick={()=>{setCategory(c);setIndex(null)}}>{c}</Button>)}</div><div className="masonry">{filtered.map((p,i)=><article className="gallery-item" key={p.id}><Button variant="ghost" aria-label={`Open photo: ${p.name}`} onClick={()=>setIndex(i)}><img src={p.image} alt={p.description} loading="lazy"/></Button><h3>{p.name}</h3><p>{p.category}</p></article>)}</div><p className="sample-note">Photographs show actual supplied creations. Collection names are illustrative, pending approval.</p></section><CustomBanner/><Dialog.Root open={index!==null} onOpenChange={open=>{if(!open)setIndex(null)}}><Dialog.Portal><Dialog.Overlay className="dialog-overlay"/>{selected&&<Dialog.Content className="lightbox"><Dialog.Title className="sr-only">{selected.name}</Dialog.Title><Dialog.Description className="sr-only">{selected.description}</Dialog.Description><img className="lightbox-image" src={selected.image} alt={selected.description}/><div className="lightbox-caption">{selected.name}<small>{(index??0)+1} / {filtered.length}</small></div><Dialog.Close asChild><Button variant="ghost" size="icon" className="lightbox-close" aria-label="Close photo"><X/></Button></Dialog.Close><Button variant="ghost" size="icon" className="lightbox-prev" aria-label="Previous photo" onClick={()=>move(-1)}><ChevronLeft/></Button><Button variant="ghost" size="icon" className="lightbox-next" aria-label="Next photo" onClick={()=>move(1)}><ChevronRight/></Button></Dialog.Content>}</Dialog.Portal></Dialog.Root></>;}
