import { useState } from 'react';
import { Link } from '@tanstack/react-router';
import { ArrowUpRight, ArrowRight, Menu, X, MessageCircle, Instagram, Heart, Package, Sparkles, Truck } from 'lucide-react';
import { Button } from '@/components/ui/button';
import icon from '@/assets/akarshan-icon.png';
import { categories, customMessage, instagram, productMessage, whatsapp, type Product } from '@/lib/catalog';
const navigation = [{to:'/',label:'Home'}, {to:'/about',label:'Our Story'}, {to:'/creations',label:'Creations'}, {to:'/gallery',label:'Gallery'}, {to:'/custom-orders',label:'Custom Orders'}, {to:'/contact',label:'Contact'}] as const;
export function Brand({ footer = false }: { footer?: boolean }) { return <Link to="/" className={`brand ${footer ? 'brand-footer' : ''}`} aria-label="Akarshan Creations home"><img src={icon} width={52} height={52} alt=""/><span>Akarshan<small>CREATIONS</small></span></Link>; }
export function Header() { const [open,setOpen] = useState(false); return <><div className="announcement"><span>Handcrafted with love</span><span className="announcement-divider">✦</span><span>Personalized creations, delivered across India</span></div><header className="site-header"><div className="header-inner"><Brand/><nav className="desktop-nav" aria-label="Main navigation">{navigation.map(n=><Link key={n.to} to={n.to} activeOptions={{exact:true}} activeProps={{className:'nav-active'}}>{n.label}</Link>)}</nav><div className="header-actions"><WhatsAppButton className="header-whatsapp">Let’s Talk <ArrowUpRight/></WhatsAppButton><Button variant="ghost" size="icon" className="menu-toggle" aria-label={open?'Close navigation':'Open navigation'} aria-expanded={open} aria-controls="mobile-nav" onClick={()=>setOpen(!open)}>{open?<X/>:<Menu/>}</Button></div></div>{open&&<nav id="mobile-nav" className="mobile-nav" aria-label="Mobile navigation">{navigation.map(n=><Link key={n.to} to={n.to} onClick={()=>setOpen(false)}>{n.label}<ArrowUpRight size={16}/></Link>)}</nav>}</header></>; }
export function WhatsAppButton({children,message,className='',variant='default'}:{children:React.ReactNode;message?:string;className?:string;variant?:'default'|'outline'|'secondary'|'ghost'}) {return <Button asChild variant={variant} className={className}><a href={whatsapp(message)} target="_blank" rel="noopener noreferrer">{children}</a></Button>;}
export function Footer(){return <footer className="site-footer"><div className="container footer-grid"><div><Brand footer/><p>Handmade art. Thoughtful gifts.<br/>A little more personal, always.</p><a href={instagram} target="_blank" rel="noopener noreferrer" aria-label="Akarshan Creations on Instagram"><Instagram size={20}/></a></div><div><h3>Explore</h3>{navigation.slice(1).map(n=><Link key={n.to} to={n.to}>{n.label}</Link>)}</div><div><h3>Our Creations</h3>{categories.slice(1).map(c=><Link key={c} to="/creations" search={{category:c}}>{c}</Link>)}</div><div><h3>Let’s connect</h3><a href={whatsapp()} target="_blank" rel="noopener noreferrer">WhatsApp us <ArrowUpRight size={14}/></a><a href="tel:+919084666012">+91 9084666012</a><span>Meerut, Uttar Pradesh, India</span><span>Delivered across India</span><Link to="/shipping-policy">Shipping Policy</Link></div></div><div className="container footer-bottom"><span>© {new Date().getFullYear()} Akarshan Creations</span><span>Made by hand. Given with heart.</span></div></footer>;}
export function CustomBanner(){return <section className="custom-banner"><div className="container custom-banner-inner"><div><span className="eyebrow">YOUR IDEA, OUR HANDS</span><h2>Have something special in mind?</h2><p>Tell us your occasion, your ideas, your little details. Let’s make it personal.</p></div><WhatsAppButton message={customMessage} variant="secondary">Discuss Your Custom Order <ArrowUpRight/></WhatsAppButton></div></section>;}
export function ProductCard({product}:{product:Product}){return <article className="product-card"><Link to="/creations" search={{product:product.id}} className="product-image-link" aria-label={`View ${product.name}`}><img src={product.image} width={600} height={750} alt={product.description} loading="lazy"/><span className="product-tag">Made personal</span><span className="product-open"><ArrowUpRight size={21}/></span></Link><div className="product-meta"><span>{product.category}</span><span>₹{product.price.toLocaleString('en-IN')} <small>sample</small></span></div><h3><Link to="/creations" search={{product:product.id}}>{product.name}</Link></h3><p>{product.description}</p><WhatsAppButton message={productMessage(product)} variant="ghost" className="product-enquire">Enquire on WhatsApp <ArrowUpRight size={15}/></WhatsAppButton></article>;}
export function PageIntro({eyebrow,title,children}:{eyebrow:string;title:string;children:React.ReactNode}){return <div className="container page-intro"><span className="eyebrow">{eyebrow}</span><h1>{title}</h1><p>{children}</p></div>;}
export function OrderingStrip(){return <section className="ordering-strip"><div className="container ordering-grid">{[{icon:Heart,title:'Handmade with heart',text:'Every creation, thoughtfully made'},{icon:Sparkles,title:'Uniquely yours',text:'Personal touches that mean more'},{icon:Package,title:'5–7 days to create',text:'Typical preparation; transit is additional'},{icon:Truck,title:'Across India',text:'From our studio to your special moment'}].map(({icon:Icon,title,text})=><div key={title}><Icon size={24} strokeWidth={1.3}/><span><strong>{title}</strong><small>{text}</small></span></div>)}</div></section>;}
export function SectionTitle({eyebrow,title,to,label}:{eyebrow:string;title:string;to?:'/creations'|'/gallery'|'/about';label?:string}){return <div className="section-heading"><div><span className="eyebrow">{eyebrow}</span><h2>{title}</h2></div>{to&&<Link className="text-link" to={to}>{label??'Explore all creations'} <ArrowRight size={17}/></Link>}</div>;}
